function showGraph() {
  var option = document.getElementById("cluster").value;
  
  const vypravec = '#c4688c',
  postava = '#78a8d1', // postava, se kterou vypravěč nebo jiná postava explicitně komunikuje
  postava2 = '#aeb6bf'; // postava, se kterou vypravěč nebo jiná postava explicitně nekomunikuje, ale komunikace je vyprávěna (např. "promluvil jsem si s X")
  
  const line = '#000000';
  const linewidth = 1.2;

  switch(option){
    case "dabel":
      Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Ďábel na skřipci'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13,}, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
                    ["narrator", "commissioner"],
                    ["narrator", "doctor"],
                    ["narrator", "servant"],
                    ["commissioner", "narrator"],
                    ["commissioner", "doctor"],
                    ["devil", "doctor"],
                    ["doctor", "narrator"],
                    ["doctor", "commissioner"],
                    ["doctor", "devil"],
                    ["doctor", "servant"],
                ], nodes: 
                    [
                    {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},
                    {id: 'commissioner',marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'doctor',marker: {radius: 20, lineWidth: linewidth, lineColor: line},color: postava},
                    {id: 'devil',marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'servant',marker: {radius: 20, lineWidth: linewidth, lineColor: line},color: postava}
                  ]
                }
              ]
          });
    break;
    case "elegie":
      Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Elegie o černých očích'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
                    ["narrator", "friend"],
                    ["friend", "narrator"],
                ], nodes: 
                    [
                    {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},
                    {id: 'friend', marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},
                  ]
                }
              ]
          });
    break;
    case "xaverius":
      Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Svatý Xaverius'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
                    ["narrator", "painter friend"],
                    ["narrator", "Xaverius"],
                    ["narrator", "Xaver's colleague"],
                    ["narrator", "old lady on the steps of the house where Xaver lives"],
                    ["narrator", "jailer"],
                    ["narrator", "clerical"],
                    ["narrator", "constable"],
                    ['Xaverius', 'narrator'],
                    ['Xaverius', 'constable'],
                    ['Xaverius', 'mother'],
                    ['mother', 'Xaverius'],
                    ['mother', 'grandmother'],
                    ['grandmother', 'Balko'],
                    ['constable', 'narrator'],
                    ['constable', 'Xaverius'],
                    ['jailer', 'narrator'],
                    ['clerical', 'narrator']
                ], nodes: 
                    [
                    // vypravěč
                    {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},

                    // hlavní postavy
                    {id: 'painter friend',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Xaverius',marker: {radius: 20, lineWidth: linewidth, lineColor: line},color: postava},
                    {id: 'Xaver\'s colleague',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'old lady on the steps of the house where Xaver lives',marker: {radius: 10, lineWidth: linewidth, lineColor: line},color: postava2},

                    // vedlejší postavy
                    {id: 'jailer',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'clerical',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'constable',marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'mother',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'grandmother',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Balko',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                  ]
                }
              ]
          });
      break;
    case "demon":
      Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Sivooký démon'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
                   ['Regina', 'strýc Robert'],
                   ["strýc Robert", "Regina"],
                   ['strýc Robert', 'Regina'],
                   ['stařenka', 'soudní komise'],
                   ['sousedka', 'zapisovatel'],
                   ['zapisovatel', 'sousedka'],
                   ['sousedka', 'zapisovatel'],
                   ['zapisovatel', 'sousedka'],
                   ['sousedka', 'zapisovatel'],
                   ['zapisovatel', 'kočí'],
                   ['hrobník', 'zapisovatel'],
                   ['narrator', 'vypravěčův přítel'],
                   ['vypravěčův přítel', 'narrator'],
                   ['narrator', 'vypravěčův přítel'],
                   ['vypravěčův přítel', 'narrator'],
                   ['narrator', 'vypravěčův přítel'],
                   ['vypravěčův přítel', 'narrator'],
                   ["strýc Robert", "narrator"],
                   ["Regina", "narrator"],
                   ["hospodský", "narrator"],
                   ["narrator", "hospodský"],
                   ["hospodský", "narrator"],
                   ["narrator", "hospodský"],
                   ["hospodský", "narrator"],
                   ["narrator", "hospodský"],
                   ["hospodský", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["narrator", "kočí"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["Regina", "narrator"],
                   ["stařena", "narrator"],
                   ["stařena", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],

                   ["strýc Robert", "Regina"],
                   ["Regina", "strýc Robert"],
                   ["strýc Robert", "Regina"],
                   ["strýc Robert", "Regina"],
                   ["Regina", "strýc Robert"],

                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],

                   ["Regina", "narrator"],
                   ["Regina", "Reginin otec"],
                   ["Regina", "Reginin otec"],
                   ["Reginin otec", "Regina"],
                   ["Regina", "Reginin otec"],
                   ["Reginin otec", "Regina"],
                   ["Reginin otec", "Regina"],
                   ["Regina", "Reginin otec"],
                   ["Reginin otec", "Regina"],
                   ["Reginin otec", "Regina"],
                   ["Reginin otec", "strýc Robert"],
                   ["Reginin otec", "strýc Robert"],

                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["strýc Robert", "Regina"],
                   ["Regina", "strýc Robert"],
                   ["strýc Robert", "Regina"],
                   ["Regina", "strýc Robert"],
                   ["strýc Robert", "Regina"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["stařena", "narrator"],
                   ["narrator", "stařena"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],

                   ["domovník", "Regina"],
                   ["Regina", "domovník"],
                   ["domovník", "Regina"],
                   ["vypravěčův přítel", "Regina"],
                   ["vypravěčův přítel", "Regina"],
                   ["Regina", "vypravěčův přítel"],
                   ["vypravěčův přítel", "Regina"],
                   ["Regina", "vypravěčův přítel"],
                   ["vypravěčův přítel", "Regina"],
                   ["Regina", "vypravěčův přítel"],
                   ["vypravěčův přítel", "Regina"],
                   ["vypravěčův přítel", "Regina"],
                   ["Regina", "vypravěčův přítel"],
                   ["vypravěčův přítel", "Regina"],
                   ["vypravěčův přítel", "Regina"],
                   ["vypravěčův přítel", "domovník"],
                   ["domovník", "vypravěčův přítel"],
                   ["vypravěčův přítel", "domovník"],
                   ["domovník", "vypravěčův přítel"],
                   ["vypravěčův přítel", "domovník"],
                   ["vypravěčův přítel", "domovník"],
                   ["domovník", "vypravěčův přítel"],
                   ["vypravěčův přítel", "Regina"],
                   ["vypravěčův přítel", "Regina"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "vypravěčův přítel"],
                   ["vypravěčův přítel", "Regina"],
                   ["Regina", "vypravěčův přítel"],
                   ["Regina", "vypravěčův přítel"],
                   ["vypravěčův přítel", "Regina"],
                   ["Regina", "vypravěčův přítel"],
                   ["vypravěčův přítel", "Regina"],
                   ["Regina", "vypravěčův přítel"],
                   ["Regina", "narrator"],
                   ["narrator", "Regina"],
                   ["Regina", "narrator"],
                   ["stařena", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],

                   ["strýc Robert", "granátníci"],
                   ["strýc Robert", "kočí"],
                   ["strýc Robert", "kočí"],

                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["kočí", "strýc Robert"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "policisté"],
                   ["adjunkt", "narrator"],
                   ["strýc Robert", "policisté"],
                   ["adjunkt", "strýc Robert"],
                   ["strýc Robert", "policisté"],
                   ["strýc Robert", "kočí"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],

                   ["strýc Robert", "čeleď"],
                   ["strýc Robert", "policisté"],
                   ["strýc Robert", "kočí"],

                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],

                   ["strýc Robert", "Regina"],
                   ["Regina", "strýc Robert"],
                   ["Regina", "strýc Robert"],
                   ["strýc Robert", "vypravěčův přítel"],
                   ["strýc Robert", "vypravěčův přítel"],

                   ["policisté", "vypravěčův přítel"],
                   ["vypravěčův přítel", "policisté"],
                   ["policisté", "vypravěčův přítel"],
                   ["adjunkt", "policisté"],
                   ["policisté", "adjunkt"],
                   ["adjunkt", "policisté"],
                   ["policisté", "adjunkt"],
                   ["adjunkt", "policisté"],
                   ["policisté", "adjunkt"],
                   ["adjunkt", "policisté"],
                   ["adjunkt", "vypravěčův přítel"],

                   ["policisté", "vypravěčův přítel"],
                   ["vypravěčův přítel", "policisté"],
                   ["policisté", "vypravěčův přítel"],
                   ["adjunkt", "policisté"],
                   ["policisté", "adjunkt"],
                   ["adjunkt", "policisté"],
                   ["policisté", "adjunkt"],
                   ["adjunkt", "policisté"],
                   ["policisté", "adjunkt"],
                   ["adjunkt", "policisté"],
                   ["adjunkt", "vypravěčův přítel"],

                   ["narrator", "vypravěčův přítel"],
                   ["strýc Robert", "čeleď"],
                   ["Regina", "strýc Robert"],

                   ["narrator", "kočí"],
                   ["kočí", "narrator"],
                   ["narrator", "kočí"],
                   ["kočí", "narrator"],

                   ["policisté", "narrator"],
                   ["kočí", "policisté"],
                   ["kočí", "policisté"],

                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["Regina", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["narrator", "strýc Robert"],
                   ["strýc Robert", "narrator"],
                   ["strýc Robert", "narrator"]
                ], nodes: 
                    [
                    {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},

                    // hlavní postavy
                    {id: 'Regina',marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'strýc Robert', marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy
                    {id: 'stařenka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'soudní komise',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'sousedka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'zapisovatel',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'kočí',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'hrobník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'vypravěčův přítel',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'hospodský',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'stařena',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Reginin otec',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'domovník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'granátníci',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'adjunkt',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'policisté',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'čeleď',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava},
                  ]
                }
              ]
          });
      break;
    case "madona":
        Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Zázračná madona'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
                   ["Matka Ismeny", "Ismena"],
                   ["Matka", "narrator"],
                   ["Matka", "narrator"],
                   ["Matka", "narrator"],
                   ["Matka", "narrator"],
                   ["Matka Ismeny", "narrator"],
                   ["narrator", "Matka Ismeny"],
                   ["Matka Ismeny", "narrator"],
                   ["narrator", "Matka Ismeny"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "Stolovníci"],
                   ["Stolovníci", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Ismena", "narrator"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["narrator", "Stolovníci"],
                   ["narrator", "Stolovníci"],
                   ["Stolovníci", "narrator"],
                   ["Stolovníci", "Stolovníci"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Otec", "narrator"],
                   ["narrator", "Otec"],
                   ["Otec", "narrator"],
                   ["Přítel", "narrator"],
                   ["Lékárník", "Ismena"],
                   ["Ismena", "Lékárník"],
                   ["Lékárník", "narrator"],
                   ["Lékárník", "Ismena"],
                   ["Lékárník", "Přítel"],
                   ["narrator", "Lékárník"],
                   ["Lékárník", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["Přítel", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Matka Ismeny", "Ismena"],
                   ["Ismena", "Matka Ismeny"],
                   ["Pěstoun", "Ismena"],
                   ["Ismena", "Pěstoun"],
                   ["Pěstoun", "Ismena"],
                   ["Ismena", "Pěstoun"],
                   ["Pěstoun", "Ismena"],
                   ["Pěstoun", "Ismena"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Přítel", "narrator"],
                   ["Přítel", "narrator"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Kočí"],
                   ["Kočí", "narrator"],
                   ["narrator", "Kočí"],
                   ["narrator", "Přítel"],
                   ["Přítel", "narrator"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Doktor"],
                   ["Doktor", "narrator"],
                   ["narrator", "Doktor"],
                   ["Doktor", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["narrator", "Ismena"],
                   ["narrator", "Ismena"],
                   ["Ismena", "narrator"],
                   ["Ismena", "narrator"]
                  ], nodes: 
                      [
                      {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},
                      
                      // hlavní postavy
                      {id: 'Ismena',marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},
                      {id: 'Přítel', marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},
                      {id: 'Pěstoun', marker: {radius: 20, lineWidth: linewidth, lineColor: line}, color: postava},
                      
                      // vedlejší postavy
                      {id: 'Doktor',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                      {id: 'Kočí',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                      {id: 'Matka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                      {id: 'Matka Ismeny',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                      {id: 'Otec',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                      {id: 'Lékárník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                      {id: 'Stolovníci',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    ]
                  }
                ]
            });
        break;
      case "ukrizovana":
        Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Ukřižovaná'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
                     []
                  ], nodes: 
                      [
                      {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},
                      
                    ]
                  }
                ]
            });
        break;
      default:
        document.getElementById("container").src = "";   
  }
}







