case "flvek2":
    Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.4205, 50.0858], zoom: 9}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: 'F. L. Věk II'}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
    {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
        {name: 'Dobytčí trh (dnes Karlovo náměstí), Praha', lon: 14.4205, lat: 50.0758, image: "../foto_praha/dobytci_trh.jpg"},
        {name: 'Kostel sv. Ignáce, Karlovo náměstí, Praha', lon: 14.4212, lat: 50.076, image: "../foto_praha/kostel_sv_ignace_karlovo_namesti_praha.jpg"},
        {name: 'Staroměstské náměstí, Praha', lon: 14.421, lat: 50.0875, image: "../foto_praha/staromestske_namesti_praha.jpg"},
        {name: 'Malé náměstí, Staré Město, Praha', lon: 14.4195, lat: 50.0865, image: "../foto_praha/male_namesti_stare_mesto_praha.jpg"},
        {name: 'Karlův (Kamenný) most, Praha', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluv.jpg"},
        {name: 'Pražský hrad, Praha', lon: 14.4001, lat: 50.0905, image: "../foto_praha/prazsky_hrad_praha.jpg"},
        {name: 'Hradčany, Praha', lon: 14.399, lat: 50.0894, image: "../foto_praha/hradcany_praha.jpg"},
        {name: 'Hradčanské náměstí, Praha', lon: 14.3985, lat: 50.089, image: "../foto_praha/hradcanske_namesti_praha.jpg"},
        {name: 'Malá Strana, Praha', lon: 14.404, lat: 50.0884, image: "../foto_praha/mala_strana_praha.jpg"},
        {name: 'Staré Město, Praha', lon: 14.421, lat: 50.0875, image: "../foto_praha/stare_mesto_praha.jpg"},
        {name: 'Nové Město, Praha', lon: 14.427, lat: 50.078, image: "../foto_praha/nove_mesto_praha.jpg"},
        {name: 'Strahovský klášter, Praha', lon: 14.3885, lat: 50.0855, image: "../foto_praha/strahovsky_klaster_praha.jpg"},
        {name: 'Emauzský klášter, Praha', lon: 14.4175, lat: 50.0719, image: "../foto_praha/emauzsky_klaster_praha.jpg"},
        {name: 'Hybernský klášter, Praha', lon: 14.4285, lat: 50.0888, image: "../foto_praha/hybernsky_klaster_praha.jpg"},
        {name: 'Křížovnický kostel sv. Františka, Praha', lon: 14.4135, lat: 50.086, image: "../foto_praha/krizovnicky_kostel_sv_frantiska_praha.jpg"},
        {name: 'Petřín, Praha', lon: 14.3915, lat: 50.0835, image: "../foto_praha/petrin_praha.jpg"},
        {name: 'Prašná brána, Praha', lon: 14.428, lat: 50.0875, image: "../foto_praha/prasna_brana_praha.jpg"},
        {name: 'Celetná ulice, Praha', lon: 14.4242, lat: 50.0873, image: "../foto_praha/celetna_ulice_praha.jpg"},
        {name: 'Železná ulice, Praha', lon: 14.422, lat: 50.0858, image: "../foto_praha/zelezna_ulice_praha.jpg"},
        {name: 'Jilská ulice, Praha', lon: 14.4185, lat: 50.085, image: "../foto_praha/jilska_ulice_praha.jpg"},
        {name: 'Michalská ulice, Praha', lon: 14.419, lat: 50.0855, image: "../foto_praha/michalska_ulice_praha.jpg"},
        {name: 'Spálená ulice, Praha', lon: 14.4195, lat: 50.081, image: "../foto_praha/spalena_ulice_praha.jpg"},
        {name: 'Ječná ulice, Praha', lon: 14.4235, lat: 50.0745, image: "../foto_praha/jecna_ulice_praha.jpg"},
        {name: 'Vodičkova ulice, Praha', lon: 14.423, lat: 50.079, image: "../foto_praha/vodickova_ulice_praha.jpg"},
        {name: 'Panská ulice, Praha', lon: 14.427, lat: 50.0838, image: "../foto_praha/panska_ulice_praha.jpg"},
        {name: 'Řeznická ulice, Praha', lon: 14.4205, lat: 50.0775, image: "../foto_praha/reznicka_ulice_praha.jpg"},
        {name: 'Lipová ulice, Praha', lon: 14.4215, lat: 50.0745, image: "../foto_praha/lipova_ulice_praha.jpg"},
        {name: 'Řetězová ulice, Praha', lon: 14.417, lat: 50.0858, image: "../foto_praha/retezova_ulice_praha.jpg"},
        {name: 'Poštovská ulice (dnes Karoliny Světlé), Praha', lon: 14.4145, lat: 50.0848, image: "../foto_praha/postovska_ulice.jpg"},
        {name: 'Vltava, Praha', lon: 14.411, lat: 50.086, image: "../foto_praha/vltava_praha.jpg"},
        {name: 'Dobruška', lon: 16.1611, lat: 50.2922, image: "../foto_praha/dobruska.jpg"},
        {name: 'Opočno', lon: 16.1147, lat: 50.2697, image: "../foto_praha/opocno.jpg"},
        {name: 'Kralíky', lon: 16.7592, lat: 50.0853, image: "../foto_praha/kraliky.jpg"},
        {name: 'Náchod', lon: 16.1656, lat: 50.4156, image: "../foto_praha/nachod.jpg"},
        {name: 'Rychnov nad Kněžnou', lon: 16.275, lat: 50.1631, image: "../foto_praha/rychnov_nad_kneznou.jpg"},
        {name: 'Jaroměř', lon: 15.9214, lat: 50.3556, image: "../foto_praha/jaromer.jpg"},
        {name: 'Orlické hory', lon: 16.45, lat: 50.2333, image: "../foto_praha/orlicke_hory.jpg"},
        {name: 'Poděbrady', lon: 15.1189, lat: 50.1425, image: "../foto_praha/podebrady.jpg"},
        {name: 'Český Brod', lon: 14.8606, lat: 50.0742, image: "../foto_praha/cesky_brod.jpg"},
        {name: 'Vídeň', lon: 16.3738, lat: 48.2082, image: "../foto_praha/viden.jpg"},
    ]},
    {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
        {name: 'Chrám Božího těla (zbořen 1791), Karlovo náměstí, Praha', lon: 14.42, lat: 50.0765, image: "../foto_praha/chram_boziho_tela.jpg"},
        {name: 'Poříčská brána (zbořena), Praha', lon: 14.431, lat: 50.09, image: "../foto_praha/poricska_brana.jpg"},
        {name: 'Špitálská brána (zbořena), Praha', lon: 14.4292, lat: 50.0895, image: "../foto_praha/spitalska_brana.jpg"},
    ]},]});
    break;