case "flvek3":
    Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.421, 50.087], zoom: 6}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: 'F. L. Věk III'}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
    {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
        {name: 'Pražský hrad', lon: 14.4001, lat: 50.0905, image: "../foto_praha/prazsky_hrad.jpg"},
        {name: 'Hradčany', lon: 14.399, lat: 50.0894, image: "../foto_praha/hradcany.jpg"},
        {name: 'Malá Strana', lon: 14.404, lat: 50.0884, image: "../foto_praha/mala_strana.jpg"},
        {name: 'Staré Město', lon: 14.421, lat: 50.0875, image: "../foto_praha/stare_mesto.jpg"},
        {name: 'Nové Město', lon: 14.427, lat: 50.078, image: "../foto_praha/nove_mesto.jpg"},
        {name: 'Josefov', lon: 14.418, lat: 50.09, image: "../foto_praha/josefov.jpg"},
        {name: 'Vltava', lon: 14.411, lat: 50.086, image: "../foto_praha/vltava.jpg"},
        {name: 'Karlův most', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluv_most.jpg"},
        {name: 'Kampa', lon: 14.4075, lat: 50.0858, image: "../foto_praha/kampa.jpg"},
        {name: 'Petřín', lon: 14.3915, lat: 50.0835, image: "../foto_praha/petrin.jpg"},
        {name: 'Letná', lon: 14.417, lat: 50.0975, image: "../foto_praha/letna.jpg"},
        {name: 'Žižkov', lon: 14.449, lat: 50.087, image: "../foto_praha/zizkov.jpg"},
        {name: 'Libeň', lon: 14.469, lat: 50.108, image: "../foto_praha/liben.jpg"},
        {name: 'Podskalí', lon: 14.415, lat: 50.066, image: "../foto_praha/podskali.jpg"},
        {name: 'Staroměstské náměstí', lon: 14.421, lat: 50.0875, image: "../foto_praha/staromestske_namesti.jpg"},
        {name: 'Koňský trh (dnes Václavské náměstí)', lon: 14.427, lat: 50.081, image: "../foto_praha/konsky_trh.jpg"},
        {name: 'Dobytčí trh (dnes Karlovo náměstí)', lon: 14.4205, lat: 50.0758, image: "../foto_praha/dobytci_trh.jpg"},
        {name: 'Ostruhová ulice (dnes Nerudova)', lon: 14.4007, lat: 50.0883, image: "../foto_praha/ostruhova_ulice.jpg"},
        {name: 'Spálená ulice', lon: 14.4195, lat: 50.081, image: "../foto_praha/spalena_ulice.jpg"},
        {name: 'Ječná ulice', lon: 14.422, lat: 50.0758, image: "../foto_praha/jecna_ulice.jpg"},
        {name: 'Mostecká ulice', lon: 14.406, lat: 50.0878, image: "../foto_praha/mostecka_ulice.jpg"},
        {name: 'Vodičkova ulice', lon: 14.4232, lat: 50.0808, image: "../foto_praha/vodickova_ulice.jpg"},
        {name: 'Dominikánská ulice (dnes Husova)', lon: 14.4185, lat: 50.0865, image: "../foto_praha/dominikanska_ulice.jpg"},
        {name: 'Jezuitská ulice (dnes Karlova)', lon: 14.4165, lat: 50.0865, image: "../foto_praha/jezuitska_ulice.jpg"},
        {name: 'Prašná brána', lon: 14.4281, lat: 50.0875, image: "../foto_praha/prasna_brana.jpg"},
        {name: 'Stavovské divadlo', lon: 14.4233, lat: 50.0866, image: "../foto_praha/stavovske_divadlo.jpg"},
        {name: 'Klášter Hybernů (U Hybernů)', lon: 14.4286, lat: 50.0889, image: "../foto_praha/hybernu.jpg"},
        {name: 'Špitál Milosrdných bratří (Na Františku)', lon: 14.4188, lat: 50.0908, image: "../foto_praha/milosrdni.jpg"},
        {name: 'Novoměstská radnice', lon: 14.4205, lat: 50.0784, image: "../foto_praha/novomestska_radnice.jpg"},
        {name: 'Kanálská zahrada', lon: 14.435, lat: 50.0742, image: "../foto_praha/kanalska_zahrada.jpg"},
        {name: 'Olšanské hřbitovy', lon: 14.472, lat: 50.082, image: "../foto_praha/olsanske_hrbitovy.jpg"},
        {name: 'Dobruška', lon: 16.1606, lat: 50.2906, image: "../foto_praha/dobruska.jpg"},
        {name: 'Opočno', lon: 16.1147, lat: 50.27, image: "../foto_praha/opocno.jpg"},
        {name: 'Třebechovice pod Orebem', lon: 16.0103, lat: 50.203, image: "../foto_praha/trebechovice.jpg"},
        {name: 'Hradec Králové', lon: 15.8328, lat: 50.2092, image: "../foto_praha/hradec_kralove.jpg"},
        {name: 'Český Brod', lon: 14.8607, lat: 50.0744, image: "../foto_praha/cesky_brod.jpg"},
        {name: 'Teplice', lon: 13.8245, lat: 50.6404, image: "../foto_praha/teplice.jpg"},
        {name: 'Karlovy Vary', lon: 12.8711, lat: 50.2329, image: "../foto_praha/karlovy_vary.jpg"},
        {name: 'Vídeň', lon: 16.3738, lat: 48.2082, image: "../foto_praha/viden.jpg"},
    ]},
    {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
        {name: 'Koňská brána (zbořena 1875)', lon: 14.429, lat: 50.0815, image: "../foto_praha/konska_brana.jpg"},
        {name: 'Poříčská brána (zbořena 1874)', lon: 14.4322, lat: 50.0908, image: "../foto_praha/poricska_brana.jpg"},
    ]},]});
    break;
