case "kondelik":
    Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.4178, 50.079], zoom: 10}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: 'Otec Kondelík a ženich Vejvara'}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
    {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
        {name: 'Pražský hrad', lon: 14.4001, lat: 50.0905, image: "../foto_praha/prazsky_hrad.jpg"},
        {name: 'Petřín', lon: 14.3915, lat: 50.0835, image: "../foto_praha/petrin.jpg"},
        {name: 'Malá Strana', lon: 14.404, lat: 50.0884, image: "../foto_praha/mala_strana.jpg"},
        {name: 'Újezd (Malá Strana)', lon: 14.404, lat: 50.083, image: "../foto_praha/ujezd.jpg"},
        {name: 'Staré Město', lon: 14.421, lat: 50.0875, image: "../foto_praha/stare_mesto.jpg"},
        {name: 'Staroměstské náměstí', lon: 14.421, lat: 50.0875, image: "../foto_praha/staromestske_namesti.jpg"},
        {name: 'Karlův most', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluv_most.jpg"},
        {name: 'Nové Město', lon: 14.427, lat: 50.078, image: "../foto_praha/nove_mesto.jpg"},
        {name: 'Václavské náměstí', lon: 14.427, lat: 50.081, image: "../foto_praha/vaclavske_namesti.jpg"},
        {name: 'Karlovo náměstí', lon: 14.4205, lat: 50.0758, image: "../foto_praha/karlovo_namesti.jpg"},
        {name: 'Novoměstská radnice', lon: 14.4214, lat: 50.078, image: "../foto_praha/novomestska_radnice.jpg"},
        {name: 'Ječná ulice', lon: 14.4234, lat: 50.0746, image: "../foto_praha/jecna_ulice.jpg"},
        {name: 'Žitná ulice', lon: 14.425, lat: 50.0758, image: "../foto_praha/zitna_ulice.jpg"},
        {name: 'Štěpánská ulice', lon: 14.427, lat: 50.079, image: "../foto_praha/stepanska_ulice.jpg"},
        {name: 'Spálená ulice', lon: 14.4195, lat: 50.081, image: "../foto_praha/spalena_ulice.jpg"},
        {name: 'Purkyňova ulice', lon: 14.4185, lat: 50.0808, image: "../foto_praha/purkynova_ulice.jpg"},
        {name: 'Vodičkova ulice', lon: 14.4225, lat: 50.0805, image: "../foto_praha/vodickova_ulice.jpg"},
        {name: 'Myslíkova ulice', lon: 14.4155, lat: 50.076, image: "../foto_praha/myslikova_ulice.jpg"},
        {name: 'Náplavní ulice', lon: 14.4143, lat: 50.0735, image: "../foto_praha/naplavni_ulice.jpg"},
        {name: 'Ovocná ulice (dnes okolí Václavského nám.)', lon: 14.424, lat: 50.0838, image: "../foto_praha/ovocna_ulice.jpg"},
        {name: 'Ferdinandova třída (dnes Národní třída)', lon: 14.4178, lat: 50.0817, image: "../foto_praha/ferdinandova_trida.jpg"},
        {name: 'Čelakovského ulice, Vinohrady (dobový název)', lon: 14.44, lat: 50.078, image: "../foto_praha/celakovskeho_ulice_vinohrady.jpg"},
        {name: 'Národní divadlo', lon: 14.4138, lat: 50.081, image: "../foto_praha/narodni_divadlo.jpg"},
        {name: 'Žofín (Slovanský ostrov)', lon: 14.413, lat: 50.079, image: "../foto_praha/zofin.jpg"},
        {name: 'Měšťanská beseda', lon: 14.4205, lat: 50.081, image: "../foto_praha/mestanska_beseda.jpg"},
        {name: 'most Palackého / nábřeží Palackého', lon: 14.4118, lat: 50.0728, image: "../foto_praha/most_palackeho_nabrezi_palackeho.jpg"},
        {name: 'Vltava', lon: 14.412, lat: 50.076, image: "../foto_praha/vltava.jpg"},
        {name: 'Podskalí', lon: 14.415, lat: 50.066, image: "../foto_praha/podskali.jpg"},
        {name: 'Vyšehrad', lon: 14.4176, lat: 50.0641, image: "../foto_praha/vysehrad.jpg"},
        {name: 'Podolí', lon: 14.4186, lat: 50.0512, image: "../foto_praha/podoli.jpg"},
        {name: 'Nusle', lon: 14.438, lat: 50.061, image: "../foto_praha/nusle.jpg"},
        {name: 'Vinohrady', lon: 14.448, lat: 50.0755, image: "../foto_praha/vinohrady.jpg"},
        {name: 'Smíchov', lon: 14.404, lat: 50.071, image: "../foto_praha/smichov.jpg"},
        {name: 'Prašná brána', lon: 14.4283, lat: 50.0875, image: "../foto_praha/prasna_brana.jpg"},
        {name: 'obora Hvězda', lon: 14.349, lat: 50.084, image: "../foto_praha/obora_hvezda.jpg"},
        {name: 'Divoká Šárka', lon: 14.326, lat: 50.095, image: "../foto_praha/divoka_sarka.jpg"},
        {name: 'Velká Chuchle', lon: 14.387, lat: 50.015, image: "../foto_praha/velka_chuchle.jpg"},
        {name: 'Zbraslav', lon: 14.392, lat: 49.9743, image: "../foto_praha/zbraslav.jpg"},
        {name: 'Černošice', lon: 14.321, lat: 49.956, image: "../foto_praha/cernosice.jpg"},
        {name: 'Karlštejn', lon: 14.188, lat: 49.9393, image: "../foto_praha/karlstejn.jpg"},
    ]},
    {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
        {name: 'Poříčská brána (zbořena 1875)', lon: 14.433, lat: 50.09, image: "../foto_praha/poricska_brana.jpg"},
    ]},]});
    break;
