case "snedenehokramu1":
    Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.41875, 50.0859], zoom: 11}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: 'U snědeného krámu I'}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
    {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
        {name: 'Pražský hrad', lon: 14.4001, lat: 50.0905, image: "../foto_praha/prazsky_hrad.jpg"},
        {name: 'Hradčany', lon: 14.399, lat: 50.0894, image: "../foto_praha/hradcany.jpg"},
        {name: 'Strahovský klášter', lon: 14.3895, lat: 50.0855, image: "../foto_praha/strahov.jpg"},
        {name: 'Loreta', lon: 14.3925, lat: 50.0892, image: "../foto_praha/loreta.jpg"},
        {name: 'Malá Strana', lon: 14.404, lat: 50.0884, image: "../foto_praha/mala_strana.jpg"},
        {name: 'Ostruhová ulice (dnes Nerudova)', lon: 14.4007, lat: 50.0883, image: "../foto_praha/ostruhova.jpg"},
        {name: 'Karlův most (Kamenný most)', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluv_most.jpg"},
        {name: 'Kampa', lon: 14.4075, lat: 50.0858, image: "../foto_praha/kampa.jpg"},
        {name: 'Petřín', lon: 14.3915, lat: 50.0835, image: "../foto_praha/petrin.jpg"},
        {name: 'Staré Město', lon: 14.421, lat: 50.0875, image: "../foto_praha/stare_mesto.jpg"},
        {name: 'Staroměstské náměstí', lon: 14.421, lat: 50.0875, image: "../foto_praha/staromestske_nam.jpg"},
        {name: 'Týnský chrám', lon: 14.4223, lat: 50.0879, image: "../foto_praha/tynsky_chram.jpg"},
        {name: 'Týnská ulice', lon: 14.4235, lat: 50.0883, image: "../foto_praha/tynska_ulice.jpg"},
        {name: 'Celetná ulice', lon: 14.425, lat: 50.0871, image: "../foto_praha/celetna_ulice.jpg"},
        {name: 'Železná ulice', lon: 14.4205, lat: 50.0855, image: "../foto_praha/zelezna_ulice.jpg"},
        {name: 'Štupartská ulice', lon: 14.4258, lat: 50.0886, image: "../foto_praha/stupartska_ulice.jpg"},
        {name: 'Betlémské náměstí', lon: 14.4172, lat: 50.0846, image: "../foto_praha/betlemske_nam.jpg"},
        {name: 'Josefov', lon: 14.418, lat: 50.09, image: "../foto_praha/josefov.jpg"},
        {name: 'Nové Město', lon: 14.427, lat: 50.078, image: "../foto_praha/nove_mesto.jpg"},
        {name: 'Václavské náměstí (Koňský trh)', lon: 14.427, lat: 50.081, image: "../foto_praha/vaclavske_nam.jpg"},
        {name: 'Spálená ulice', lon: 14.4195, lat: 50.081, image: "../foto_praha/spalena_ulice.jpg"},
        {name: 'Jindřišská ulice', lon: 14.4283, lat: 50.0837, image: "../foto_praha/jindrisska_ulice.jpg"},
        {name: 'Štěpánská ulice', lon: 14.4262, lat: 50.0782, image: "../foto_praha/stepanska_ulice.jpg"},
        {name: 'Vltava', lon: 14.411, lat: 50.086, image: "../foto_praha/vltava.jpg"},
        {name: 'Vyšehrad', lon: 14.4176, lat: 50.0641, image: "../foto_praha/vysehrad.jpg"},
        {name: 'Podskalí', lon: 14.415, lat: 50.066, image: "../foto_praha/podskali.jpg"},
        {name: 'Na Skalce (kostel sv. Jana Nepomuckého)', lon: 14.4196, lat: 50.0709, image: "../foto_praha/skalka.jpg"},
        {name: 'Smíchov', lon: 14.404, lat: 50.071, image: "../foto_praha/smichov.jpg"},
        {name: 'Žižkov', lon: 14.449, lat: 50.087, image: "../foto_praha/zizkov.jpg"},
        {name: 'Vinohrady', lon: 14.448, lat: 50.0755, image: "../foto_praha/vinohrady.jpg"},
        {name: 'Libeň', lon: 14.469, lat: 50.108, image: "../foto_praha/liben.jpg"},
        {name: 'Bílá hora', lon: 14.318, lat: 50.082, image: "../foto_praha/bila_hora.jpg"},
        {name: 'Dobruška', lon: 16.1606, lat: 50.2925, image: "../foto_praha/dobruska.jpg"},
        {name: 'Kopidlno', lon: 15.2726, lat: 50.3312, image: "../foto_praha/kopidlno.jpg"},
        {name: 'Velké Meziříčí', lon: 16.0125, lat: 49.355, image: "../foto_praha/velke_mezirici.jpg"},
        {name: 'Mašťov', lon: 13.2386, lat: 50.2783, image: "../foto_praha/mastov.jpg"},
        {name: 'Jezuitská zahrada (orientačně)', lon: 14.4175, lat: 50.0865, image: "../foto_praha/jezuitska_zahrada.jpg"},
    ]},
    {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
        {name: 'Koňská brána (zbořena 1875)', lon: 14.429, lat: 50.0815, image: "../foto_praha/konska_brana.jpg"},
        {name: 'Špitálská (Poříčská) brána (zbořena)', lon: 14.434, lat: 50.0905, image: "../foto_praha/spitalska_brana.jpg"},
        {name: 'Zderazská brána (zbořena)', lon: 14.4155, lat: 50.0772, image: "../foto_praha/zderazska_brana.jpg"},
    ]},]});
    break;