case "snedeneho_kramu_iv":
    Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.4150, 50.0805], zoom: 13}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: 'U snědeného krámu IV'}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
    {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
        {name: 'Podskalí', lon: 14.4150, lat: 50.0660, image: "../foto_praha/podskali.jpg"},
        {name: 'Karlovo náměstí (Dobytčí trh)', lon: 14.4205, lat: 50.0758, image: "../foto_praha/karlovo_nam.jpg"},
        {name: 'Na Moráni', lon: 14.4155, lat: 50.0726, image: "../foto_praha/na_morani.jpg"},
        {name: 'Spálená ulice', lon: 14.4195, lat: 50.0810, image: "../foto_praha/spalena_ulice.jpg"},
        {name: 'Kostel Nejsvětější Trojice (Trojický kostel)', lon: 14.4189, lat: 50.0801, image: "../foto_praha/trojicky_kostel.jpg"},
        {name: 'Václavská ulice', lon: 14.4175, lat: 50.0738, image: "../foto_praha/vaclavska_ulice.jpg"},
        {name: 'Vodičkova ulice', lon: 14.4232, lat: 50.0808, image: "../foto_praha/vodickova_ulice.jpg"},
        {name: 'Václavské náměstí', lon: 14.4280, lat: 50.0810, image: "../foto_praha/vaclavske_nam.jpg"},
        {name: 'Žitnobranská ulice (u býv. Žitné brány)', lon: 14.4293, lat: 50.0803, image: "../foto_praha/zitnobranska_ulice.jpg"},
        {name: 'Ferdinandova třída (dnes Národní)', lon: 14.4178, lat: 50.0817, image: "../foto_praha/ferdinandova_trida.jpg"},
        {name: 'Novoměstská radnice', lon: 14.4216, lat: 50.0782, image: "../foto_praha/novomestska_radnice.jpg"},
        {name: 'Staroměstské náměstí', lon: 14.4210, lat: 50.0875, image: "../foto_praha/staromestske_nam.jpg"},
        {name: 'Celetná ulice', lon: 14.4250, lat: 50.0871, image: "../foto_praha/celetna_ulice.jpg"},
        {name: 'Josefské náměstí (dnes náměstí Republiky)', lon: 14.4280, lat: 50.0890, image: "../foto_praha/josefske_nam.jpg"},
        {name: 'Na Příkopě (Příkopy)', lon: 14.4255, lat: 50.0855, image: "../foto_praha/prikopy.jpg"},
        {name: 'Ovocná ulice', lon: 14.4225, lat: 50.0858, image: "../foto_praha/ovocna_ulice.jpg"},
        {name: 'Hybernská ulice (Hyberňácká)', lon: 14.4320, lat: 50.0878, image: "../foto_praha/hybernska_ulice.jpg"},
        {name: 'Mariánské náměstí', lon: 14.4178, lat: 50.0872, image: "../foto_praha/marianske_nam.jpg"},
        {name: 'Platnéřská ulice', lon: 14.4165, lat: 50.0880, image: "../foto_praha/platnerska_ulice.jpg"},
        {name: 'Mostecká ulice', lon: 14.4060, lat: 50.0875, image: "../foto_praha/mostecka_ulice.jpg"},
        {name: 'Malostranské náměstí', lon: 14.4036, lat: 50.0879, image: "../foto_praha/malostranske_nam.jpg"},
        {name: 'Malá Strana', lon: 14.4040, lat: 50.0884, image: "../foto_praha/mala_strana.jpg"},
        {name: 'Ostruhová ulice (dnes Nerudova)', lon: 14.4007, lat: 50.0883, image: "../foto_praha/ostruhova_ulice.jpg"},
        {name: 'Újezd', lon: 14.4040, lat: 50.0830, image: "../foto_praha/ujezd.jpg"},
        {name: 'Smíchov', lon: 14.4040, lat: 50.0710, image: "../foto_praha/smichov.jpg"},
        {name: 'Kamenný most (dnes Karlův most)', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluv_most.jpg"},
        {name: 'Emauzy (klášter Na Slovanech)', lon: 14.4175, lat: 50.0719, image: "../foto_praha/emauzy.jpg"},
    ]},
    {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
        {name: 'Řetězový most (most císaře Františka I., zbořen 1898)', lon: 14.4126, lat: 50.0808, image: "../foto_praha/retezovy_most.jpg"},
    ]},]});
    break;
